version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm i npm@latest -g
      - npm install
  build:
    commands:
      - npm run-script build
  # post_build:
  #   commands:
  #     npm run-script deploy
  #     #- aws s3 sync ./public s3://elasticbeanstalk-eu-central-1-403039540759

artifacts:
  files:
    - '**/*'
  name: Blog by Philipp Schmid
  base-directory: public
